### PR TITLE
allow quill v2 beta in peerDependencies

### PR DESCRIPTION
**Pull request by dohomi**
According to the docs v2 beta has zero API changes. I want to try out the new beta due to ViteJS errors on production builds with v1

### CODE REVIEW

**Comment by dohomi** [comment]
I also remove the require('quil') statement because it prevents ViteJS from building. Seems its actually not necessary at all because its already imported on top of the file.

**Comment by gtgalone** [comment]
Hi @dohomi 

Thanks for this PR!

I just have updated version with your changes!

**Comment by itsUndefined** [comment]
Just FYI this is a breaking change. Removing the require call inside the useEffect exposes the quill at the top of the file making the code run on server side environments where quill is not supported. My webpack build stopped working after updating from 1.3.1 to 1.3.2

**Comment by dohomi** [comment]
Isn't Quill imported on top of the file? I only fixed the quill import for ViteJS, maybe to be more complient the useEffect hook could make sure that window is defined to prevent breaking on SSR environments

**Comment by dohomi** [comment]
@itsUndefined can you check if #55 fixes your build?

**Comment by itsUndefined** [comment]
It doesn't. Use effect does not run on the server anyways.

**Comment by dohomi** [comment]
useEffect runs on server and client side

**Comment by dohomi** [comment]
@gtgalone feel free to revert the changes of my PR, on NextJS and ViteJS the config compiles just fine (at least in my setup) but if other users have issues some more tests would need to be applied to prevent a regression

**Comment by gtgalone** [comment]
Hi! @itsUndefined 

I just deployed with reverting require('quill').

Please use v1.3.3

 Thanks!

**Pull request merged**
